version: '3'

services:
  traefik:
    # The latest official supported Traefik docker image
    image: traefik:v2.3
    # Enables the Traefik Dashboard and tells Traefik to listen to docker
    # enable --log.level=INFO so we can see what Traefik is doing in the log files
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      - "443:443"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Copies the Let's Encrypt certificate locally for ease of backing up
      - ./letsencrypt:/letsencrypt
       # Mounts the Traefik static configuration inside the Traefik container
      - ./traefik.tls.yml:/etc/traefik/traefik.yml

# Add the catapp service
  catapp:
     image: mikesir87/cats:1.0
     labels:
        - "traefik.enable=true"
        - "traefik.http.services.catapp.loadbalancer.server.port=5000"
        - "traefik.http.routers.catapp.rule=Host(`tech-takeaway.com`)"
        - "traefik.http.routers.catapp.service=catapp"
        - "traefik.http.routers.catapp.entrypoints=web"
        - "traefik.http.routers.catapp.tls.certresolver=myresolver"
        - "traefik.http.routers.catapp.middlewares=redirect"
        - "traefik.http.routers.catapp-secure.rule=Host(`tech-takeaway.com`)"
        - "traefik.http.routers.catapp-secure.entrypoints=websecure"
        - "traefik.http.routers.catapp-secure.tls.certresolver=myresolver"
        - "traefik.http.routers.catapp-secure.middlewares=ratelimit,my-compress"
        # Middlewares
        - "traefik.http.middlewares.my-compress.compress=true"
        - "traefik.http.middlewares.ratelimit.ratelimit.average=5"
    # Redirect Scheme HTTP -> HTTPS
        - "traefik.http.middlewares.my-redirectscheme.redirectscheme.scheme=https"
        - "traefik.http.middlewares.my-redirectscheme.redirectscheme.permanent=true"